apiVersion: v1
kind: Service
metadata:
  name: nodejs-api-service
  namespace: devops-app
  labels:
    app: nodejs-api
spec:
  type: NodePort
  selector:
    app: nodejs-api
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: http
